api/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from .views import RubricList, RubricDetail, AdList, AdDetail

urlpatterns = [
    path('rubrics/', RubricList.as_view()),
    path('rubrics/<int:pk>/', RubricDetail.as_view()),
    path('ads/all', AdList.as_view()),
    path('ads/<int:pk>/', AdDetail.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

callboard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('api.urls')),
    path('captcha/', include('captcha.urls')),
    path('', include('main.urls'))
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # маршрут для обработки static files

main/urls.py
from django.urls import path

from .views import index, other_page, BBLoginView, profile, BBLogoutView, ChangeUserInfoView, BBPasswordChangeView, \
    RegisterUserView, RegisterDoneView, user_activate, DeleteUserView, by_rubric, detail, profile_ad_detail, \
    profile_ad_add, profile_ad_change, profile_ad_delete

app_name = 'main'
urlpatterns = [
    path('', index, name='index'),
    path('<int:rubric_pk>/<int:pk>/', detail, name='detail'),
    path('<int:pk>/', by_rubric, name='by_rubric'),
    path('<str:page>/', other_page, name='other'),
    path('accounts/login/', BBLoginView.as_view(), name='login'),  # accounts/login/ - путь для авторизации
    # пользователей в джанго по умолчанию
    path('accounts/profile/change/<int:pk>', profile_ad_change, name='profile_ad_change'),
    path('accounts/profile/delete/<int:pk>', profile_ad_delete, name='profile_ad_delete'),
    path('accounts/profile/add', profile_ad_add, name='profile_ad_add'),
    path('accounts/profile/<int:pk>/', profile_ad_detail, name='profile_ad_detail'),
    path('accounts/profile/', profile, name='profile'),  # accounts/profile/ - путь, по которому Django по умолчанию
    # перенаправляет пользователя при успешном входе
    path('accounts/logout/', BBLogoutView.as_view(), name='logout'),
    path('accounts/profile/change/', ChangeUserInfoView.as_view(), name='profile_change'),
    path('accounts/password/change/', BBPasswordChangeView.as_view(), name='password_change'),
    path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register/', RegisterUserView.as_view(), name='register'),
    path('accounts/login/', BBLoginView.as_view(), name='login'),
    path('accounts/register/activate/<str:sign>/', user_activate, name='register_activate'),
    path('accounts/profile/delete/', DeleteUserView.as_view(), name='profile_delete'),
]

main/forms.py
from django import forms
from django.forms import ModelForm, TextInput
from .models import AdvUser
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError
from django.forms import inlineformset_factory
from captcha.fields import CaptchaField

from .apps import user_registered
from .models import SuperRubric, SubRubric, Ad, AdditionalImage, Comment


class ChangeUserInfoForm(forms.ModelForm):
    email = forms.EmailField(required=True, label="Адрес электронной почты") #Поле формы сделали обязательным для заполнения

    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'first_name', 'last_name', 'send_messages')

        widgets = {'username': TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Поле для ввода текста'
        })
        }


class RegisterUserForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Адрес электронной почты')
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput,
                                help_text=password_validation.password_validators_help_text_html())
    password2 = forms.CharField(label='Повторный ввод пароля', widget=forms.PasswordInput,
                                help_text='Введите пароль еще раз')

    def clean_password1(self):
        password1 = self.cleaned_data['password1']
        if password1:
            password_validation.validate_password(password1)
            return password1

    def clean(self):
        super().clean()
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 and password2 and password1 != password2:
            errors = {'password2': ValidationError(
                'Введенные пароли не совпадают', code='password-mismatch')}
            raise ValidationError(errors)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.is_active = False
        user.is_activated = False
        if commit:
            user.save()
        user_registered.send(RegisterUserForm, instance=user)
        return user

    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'password1', 'password2',
                  'first_name', 'last_name', 'send_messages')


class SubRubricForm(forms.ModelForm):
    super_rubric = forms.ModelChoiceField(queryset=SuperRubric.objects.all(), empty_label=None,
                                          label='Надрубрика', required=True)

    class Meta:
        model = SubRubric
        fields = '__all__'


class SearchForm(forms.Form):
    keyword = forms.CharField(required=False, max_length=20, label='')


class AdForm(forms.ModelForm):
    class Meta:
        model = Ad
        fields = "__all__"
        widgets = {'author': forms.HiddenInput}

AIFormSet = inlineformset_factory(Ad, AdditionalImage, fields="__all__")


class UserCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ('is_active',)
        widgets = {'ad': forms.HiddenInput}


class GuestCommentForm(forms.ModelForm):
    captcha = CaptchaField(label='Введите текст с картинки',
                           error_messages={'invalid': 'Неправильный текст'})

    class Meta:
        model = Comment
        exclude = ('is_active',)
        widgets = {'ad': forms.HiddenInput}

main/views.py
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import Paginator
from django.core.signing import BadSignature
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.template import TemplateDoesNotExist
from django.template.loader import get_template
from django.http import HttpResponse, Http404
from django.urls import reverse_lazy
from django.views.generic import UpdateView, CreateView, TemplateView, DeleteView

from .models import AdvUser, SubRubric, Ad, Comment, Rubric
from .forms import ChangeUserInfoForm, RegisterUserForm, SearchForm, AdForm, AIFormSet, UserCommentForm, \
    GuestCommentForm
from .utilities import signer


def index(request):
    ads = Ad.objects.filter(is_active=True)[:10]
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        q = Q(title__icontains=keyword) | Q(content__icontains=keyword)
        ads = ads.filter(q)
    else:
        keyword = ''
    form = SearchForm(initial={'keyword': keyword})
    paginator = Paginator(ads, 2)
    if 'page' in request.GET:
        page_num = request.GET['page']
    else:
        page_num = 1
    page = paginator.get_page(page_num)
    context = {'page': page, 'ads': page.object_list, 'form': form}
    return render(request, 'main/index.html', context)


def by_rubric(request, pk):
    rubric = get_object_or_404(SubRubric, pk=pk)
    ads = Ad.objects.filter(is_active=True, rubric=pk)
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        q = Q(title__icontains=keyword) | Q(content__icontains=keyword)
        ads = ads.filter(q)
    else:
        keyword = ''
    form = SearchForm(initial={'keyword': keyword})
    paginator = Paginator(ads, 2)
    if 'page' in request.GET:
        page_num = request.GET['page']
    else:
        page_num = 1
    page = paginator.get_page(page_num)
    context = {'rubric': rubric, 'page': page, 'ads': page.object_list, 'form': form}
    return render(request, 'main/by_rubric.html', context)


def detail(request, rubric_pk, pk):
    ad = get_object_or_404(Ad, pk=pk)
    ais = ad.additionalimage_set.all()
    comments = Comment.objects.filter(ad=pk, is_active=True)
    initial = {'ad': ad.pk}
    if request.user.is_authenticated:
        initial['author'] = request.user.username
        form_class = UserCommentForm
    else:
        form_class = GuestCommentForm
    form = form_class(initial=initial)
    if request.method == 'POST':
        c_form = form_class(request.POST)
        if c_form.is_valid():
            c_form.save()
            messages.add_message(request, messages.SUCCESS, 'Комментарий добавлен')
        else:
            form = c_form
            messages.add_message(request, messages.WARNING, 'Комментарий не добавлен')

    context = {'ad': ad, 'ais': ais, 'comments': comments, 'form': form}
    return render(request, 'main/detail.html', context)


def user_activate(request, sign):
    """Контоллер активации нового пользователя"""
    try:
        username = signer.unsign(sign)
    except BadSignature:
        return render(request, 'main/bad_signature.html')
    user = get_object_or_404(AdvUser, username=username)
    if user.is_activated:
        template = 'main/user_is_activated.html'
    else:
        template = 'main/activation_done.html'
        user.is_active = True
        user.is_activated = True
    return render(request, template)


def other_page(request, page):
    ''''''
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))


#Контроллеры просмотра редактирования и  удаления объявлений пользователя
@login_required
def profile(request):
    '''декоратор дает доступ к странице только авторизованным пользователям'''
    ads = Ad.objects.filter(author=request.user.pk)
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        q = Q(title__icontains=keyword) | Q(content__icontains=keyword)
        ads = ads.filter(q)
    else:
        keyword = ''
    form = SearchForm(initial={'keyword': keyword})
    paginator = Paginator(ads, 2)
    if 'page' in request.GET:
        page_num = request.GET['page']
    else:
        page_num = 1
    page = paginator.get_page(page_num)
    context = {'page': page, 'ads': page.object_list, 'form': form}
    return render(request, 'main/profile.html', context)


@login_required
def profile_ad_detail(request, rubric_pk, pk):
    ad = get_object_or_404(Ad, pk=pk)
    ais = ad.additionalimage_set.all()
    context = {'ad': ad, 'ais': ais}
    return render(request, 'main/profile_ad_detail.html', context)


@login_required
def profile_ad_add(request):
    if request.method == 'POST':
        form = AdForm(request.POST, request.FILES)
        if form.is_valid():
            ad = form.save()
            formset = AIFormSet(request.POST, request.FILES, instance=ad)
            if formset.is_valid():
                formset.save()
                messages.add_message(request, messages.SUCCESS, 'Объявление добавлено')
                return redirect('main:profile')
    else:
        form = AdForm(initial={'author': request.user.pk})
        formset = AIFormSet()
    context = {'form': form, 'formset': formset}
    return render(request, 'main/profile_ad_add.html', context)


@login_required
def profile_ad_change(request, pk):
    ad = get_object_or_404(Ad, pk=pk)
    if request.method == 'POST':
        form = AdForm(request.POST, request.FILES, instance=ad)
        if form.is_valid():
            ad = form.save()
            formset = AIFormSet(request.POST, request.FILES, instance=ad)
            if formset.is_valid():
                formset.save()
                messages.add_message(request, messages.SUCCESS, 'Объявление изменено')
                return redirect('main:profile')
    else:
        form = AdForm(instance=ad)
        formset = AIFormSet(instance=ad)
    context = {'form': form, 'formset': formset}
    return render(request, 'main/profile_ad_change.html', context)


@login_required
def profile_ad_delete(request, pk):
    ad = get_object_or_404(Ad, pk=pk)
    if request.method == "POST":
        ad.delete()
        messages.add_message(request, messages.SUCCESS, 'Объявление удалено')
        return redirect('main:profile')
    else:
        context = {'ad': ad}
        return render(request, 'main/profile_ad_delete.html')


# class-based контроллеры для регистрации, редактирования личных данных и удаления профиля пользователя
class BBLoginView(LoginView):
    template_name = 'main/login.html'


class BBLogoutView(LogoutView, LoginRequiredMixin):
    '''Страница выхода должна быть доступна только зарегистрированным пользователям,
    выполнившим вход. Поэтому в число суперклассов добавили LoginRequiredMixin'''
    template_name = 'main/logout.html'

class BBPasswordChangeView(SuccessMessageMixin, LoginRequiredMixin, PasswordChangeView):
    '''В качестве одного из суперклассов этого контроллера-класса мы указали примесь
LoginRequiredMixin, запрещающую доступ к контроллеру гостям, и примесь
SuccessMessageMixin, которая применяется для вывода всплывающих сообщений
об успешном выполнении операции.'''
    template_name = 'main/password_change.html'
    success_url = reverse_lazy('main:profile')
    success_message = "Ваш пароль был успешно изменен"


class ChangeUserInfoView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    """В процессе работы этот контроллер должен извлечь из модели AdvUser запись,
представляющую текущего пользователя, для чего ему нужно предварительно
получить ключ текущего пользователя. Получить его можно из объекта текущего
пользователя, хранящегося в атрибуте user объекта запроса.
В качестве одного из суперклассов этого контроллера-класса мы указали примесь
LoginRequiredMixin, запрещающую доступ к контроллеру гостям, и примесь
SuccessMessageMixin, которая применяется для вывода всплывающих сообщений
об успешном выполнении операции."""
    model = AdvUser
    template_name = 'main/change_user_info.html'
    form_class = ChangeUserInfoForm
    success_url = reverse_lazy('main:profile')
    success_message = "Ваши данные пользователя были изменены"

    def setup(self, request, *args, **kwargs):
        """Вероятно, наилучшее место для получения ключа текущего пользователя — метод
setup, наследуемый всеми контроллерами-классами от их общего суперкласса
view. Этот метод выполняется в самом начале исполнения контроллера-класса и
получает объект запроса в качестве одного из параметров. В переопределенном
методе setup () мы извлечем ключ пользователя и сохраним его в атрибуте user id."""
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)

    def get_object(self, queryset=None):
        """Извлечение исправляемой записи выполняем в методе get object, который контроллер-
класс унаследовал от примеси singieobjectMixin. В переопределенном методе
сначала учитываем тот момент, что набор записей, из которого следует извлечь
искомую запись, может быть передан методу с параметром queryset, а может
быть и не передан — в этом случае набор записей следует получить вызовом метода
get queryset (). После этого непосредственно ищем запись, представляющую
текущего пользователя."""
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


class RegisterUserView(CreateView):
    model = AdvUser
    template_name = 'main/register_user.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('main:register_done')


class RegisterDoneView(TemplateView):

main/templates/layout/basic.html
{% load static %}
{% load thumbnail %}
{% load bootstrap4 %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Главная{% endblock %} - Доска объявлений</title>
    <link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}">
    {#Bootstrap#}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"
          integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
            integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
            integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
            crossorigin="anonymous"></script>
    {#font-awesome#}
    <link rel="stylesheet" type="text/css" href="{% static 'font-awesome-4.7.0/css/font-awesome.min.css' %}">
</head>

<body>
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <ul class="navbar-nav mr-auto">
                <a class="nav-link px-4 text-info font-weight-bold text-start" href="{% url 'main:other' page='about'%}">О сайте</a>
                <li><a href="{% url 'main:index' %}" class="nav-link px-4 text-info font-weight-bold text-start">Главная</a></li>
                <a href="{% url 'main:profile_ad_add' %}" class="nav-link px-4 text-info font-weight-bold text-start">Добавить объявление</a>
            </ul>
            {% if user.is_authenticated %}
                <div class="dropdown">
                    <button class="btn btn-info dropdown-toggle" type="button" id="dropdownMenuButton1"
                            data-bs-toggle="dropdown" aria-expanded="false">
                        Профиль
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                        <li><a href="{% url 'main:profile' %}" class="dropdown-item">Мои объявления</a></li>
                        <li><a href="{% url 'main:profile_change' %}" class="dropdown-item">Изменить личные данные</a>
                        </li>
                        <li><a href="{% url 'main:password_change' %}" class="dropdown-item">Изменить пароль</a></li>
                        <div class="dropdown-divider"></div>
                        <li><a href="{% url 'main:logout' %}" class="dropdown-item">Выйти</a></li>
                        <div class="dropdown-divider"></div>
                        <li><a href="{% url 'main:profile_delete' %}" class="dropdown-item text-danger">Удалить профиль</a></li>
                    </ul>
                </div>
                <div class="text-end">
            {% else %}
                <a href="{% url 'main:register' %}" class="btn btn-outline-light me-2">Зарегистрироваться</a>
                <a href="{% url 'main:login' %}" class="btn btn-info">Войти</a>
            {% endif %}
            </div>
        </div>
</nav>
<div class="flex-shrink-0 p-3 bg-dark" id="nav-sidebar">
    {% for rubric in rubrics %}
    <ul class="list-unstyled ps-0">
      {% ifchanged rubric.super_rubric.pk %}
            <li class="mb-1">
        <button class="btn btn-toggle text-white align-items-center rounded collapsed" data-bs-toggle="collapse"
                data-bs-target="#home-collapse" aria-expanded="true">{{ rubric.super_rubric.name }}
        </button>
        {% endifchanged %}
        <div class="collapse show" id="home-collapse">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><a href="{% url 'main:by_rubric' pk=rubric.pk %}" class="text-white">{{ rubric.name }}</a></li>
          </ul>
        </div>
      </li>
    </ul>
    {% endfor %}
</div>
<div id="content">
{% block content %}
{% endblock %}
</div>
</body>
</html>