api/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from .views import RubricList, RubricDetail, AdList, AdDetail

urlpatterns = [
    path('rubrics/', RubricList.as_view()),
    path('rubrics/<int:pk>/', RubricDetail.as_view()),
    path('ads/all', AdList.as_view()),
    path('ads/<int:pk>/', AdDetail.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

callboard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('api.urls')),
    path('captcha/', include('captcha.urls')),
    path('', include('main.urls'))
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # маршрут для обработки static files

main/urls.py
from django.urls import path

from .views import index, other_page, BBLoginView, profile, BBLogoutView, ChangeUserInfoView, BBPasswordChangeView, \
    RegisterUserView, RegisterDoneView, user_activate, DeleteUserView, by_rubric, detail, profile_ad_detail, \
    profile_ad_add, profile_ad_change, profile_ad_delete

app_name = 'main'
urlpatterns = [
    path('', index, name='index'),
    path('<int:rubric_pk>/<int:pk>/', detail, name='detail'),
    path('<int:pk>/', by_rubric, name='by_rubric'),
    path('<str:page>/', other_page, name='other'),
    path('accounts/login/', BBLoginView.as_view(), name='login'),  # accounts/login/ - путь для авторизации
    # пользователей в джанго по умолчанию
    path('accounts/profile/change/<int:pk>', profile_ad_change, name='profile_ad_change'),
    path('accounts/profile/delete/<int:pk>', profile_ad_delete, name='profile_ad_delete'),
    path('accounts/profile/add', profile_ad_add, name='profile_ad_add'),
    path('accounts/profile/<int:pk>/', profile_ad_detail, name='profile_ad_detail'),
    path('accounts/profile/', profile, name='profile'),  # accounts/profile/ - путь, по которому Django по умолчанию
    # перенаправляет пользователя при успешном входе
    path('accounts/logout/', BBLogoutView.as_view(), name='logout'),
    path('accounts/profile/change/', ChangeUserInfoView.as_view(), name='profile_change'),
    path('accounts/password/change/', BBPasswordChangeView.as_view(), name='password_change'),
    path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register/', RegisterUserView.as_view(), name='register'),
    path('accounts/login/', BBLoginView.as_view(), name='login'),
    path('accounts/register/activate/<str:sign>/', user_activate, name='register_activate'),
    path('accounts/profile/delete/', DeleteUserView.as_view(), name='profile_delete'),
]

main/forms.py
from django import forms
from django.forms import ModelForm, TextInput
from .models import AdvUser
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError
from django.forms import inlineformset_factory
from captcha.fields import CaptchaField

from .apps import user_registered
from .models import SuperRubric, SubRubric, Ad, AdditionalImage, Comment


class ChangeUserInfoForm(forms.ModelForm):
    email = forms.EmailField(required=True, label="Адрес электронной почты") #Поле формы сделали обязательным для заполнения

    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'first_name', 'last_name', 'send_messages')

        widgets = {'username': TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Поле для ввода текста'
        })
        }


class RegisterUserForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Адрес электронной почты')
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput,
                                help_text=password_validation.password_validators_help_text_html())
    password2 = forms.CharField(label='Повторный ввод пароля', widget=forms.PasswordInput,
                                help_text='Введите пароль еще раз')

    def clean_password1(self):
        password1 = self.cleaned_data['password1']
        if password1:
            password_validation.validate_password(password1)
            return password1

    def clean(self):
        super().clean()
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 and password2 and password1 != password2:
            errors = {'password2': ValidationError(
                'Введенные пароли не совпадают', code='password-mismatch')}
            raise ValidationError(errors)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.is_active = False
        user.is_activated = False
        if commit:
            user.save()
        user_registered.send(RegisterUserForm, instance=user)
        return user

    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'password1', 'password2',
                  'first_name', 'last_name', 'send_messages')


class SubRubricForm(forms.ModelForm):
    super_rubric = forms.ModelChoiceField(queryset=SuperRubric.objects.all(), empty_label=None,
                                          label='Надрубрика', required=True)

    class Meta:
        model = SubRubric
        fields = '__all__'


class SearchForm(forms.Form):
    keyword = forms.CharField(required=False, max_length=20, label='')


class AdForm(forms.ModelForm):
    class Meta:
        model = Ad
        fields = "__all__"
        widgets = {'author': forms.HiddenInput}

AIFormSet = inlineformset_factory(Ad, AdditionalImage, fields="__all__")


class UserCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ('is_active',)
        widgets = {'ad': forms.HiddenInput}


class GuestCommentForm(forms.ModelForm):
    captcha = CaptchaField(label='Введите текст с картинки',
                           error_messages={'invalid': 'Неправильный текст'})

    class Meta:
        model = Comment
        exclude = ('is_active',)
        widgets = {'ad': forms.HiddenInput}

main/views.py
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import Paginator
from django.core.signing import BadSignature
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.template import TemplateDoesNotExist
from django.template.loader import get_template
from django.http import HttpResponse, Http404
from django.urls import reverse_lazy
from django.views.generic import UpdateView, CreateView, TemplateView, DeleteView

from .models import AdvUser, SubRubric, Ad, Comment, Rubric
from .forms import ChangeUserInfoForm, RegisterUserForm, SearchForm, AdForm, AIFormSet, UserCommentForm, \
    GuestCommentForm
from .utilities import signer


def index(request):
    ads = Ad.objects.filter(is_active=True)[:10]
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        q = Q(title__icontains=keyword) | Q(content__icontains=keyword)
        ads = ads.filter(q)
    else:
        keyword = ''
    form = SearchForm(initial={'keyword': keyword})
    paginator = Paginator(ads, 2)
    if 'page' in request.GET:
        page_num = request.GET['page']
    else:
        page_num = 1
    page = paginator.get_page(page_num)
    context = {'page': page, 'ads': page.object_list, 'form': form}
    return render(request, 'main/index.html', context)


def by_rubric(request, pk):
    rubric = get_object_or_404(SubRubric, pk=pk)
    ads = Ad.objects.filter(is_active=True, rubric=pk)
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        q = Q(title__icontains=keyword) | Q(content__icontains=keyword)
        ads = ads.filter(q)
    else:
        keyword = ''
    form = SearchForm(initial={'keyword': keyword})
    paginator = Paginator(ads, 2)
    if 'page' in request.GET:
        page_num = request.GET['page']
    else:
        page_num = 1
    page = paginator.get_page(page_num)
    context = {'rubric': rubric, 'page': page, 'ads': page.object_list, 'form': form}
    return render(request, 'main/by_rubric.html', context)


def detail(request, rubric_pk, pk):
    ad = get_object_or_404(Ad, pk=pk)
    ais = ad.additionalimage_set.all()
    comments = Comment.objects.filter(ad=pk, is_active=True)
    initial = {'ad': ad.pk}
    if request.user.is_authenticated:
        initial['author'] = request.user.username
        form_class = UserCommentForm
    else:
        form_class = GuestCommentForm
    form = form_class(initial=initial)
    if request.method == 'POST':
        c_form = form_class(request.POST)
        if c_form.is_valid():
            c_form.save()
            messages.add_message(request, messages.SUCCESS, 'Комментарий добавлен')
        else:
            form = c_form
            messages.add_message(request, messages.WARNING, 'Комментарий не добавлен')

    context = {'ad': ad, 'ais': ais, 'comments': comments, 'form': form}
    return render(request, 'main/detail.html', context)


def user_activate(request, sign):
    """Контоллер активации нового пользователя"""
    try:
        username = signer.unsign(sign)
    except BadSignature:
        return render(request, 'main/bad_signature.html')
    user = get_object_or_404(AdvUser, username=username)
    if user.is_activated:
        template = 'main/user_is_activated.html'
    else:
        template = 'main/activation_done.html'
        user.is_active = True
        user.is_activated = True
    return render(request, template)


def other_page(request, page):
    ''''''
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))


#Контроллеры просмотра редактирования и  удаления объявлений пользователя
@login_required
def profile(request):
    '''декоратор дает доступ к странице только авторизованным пользователям'''
    ads = Ad.objects.filter(author=request.user.pk)
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        q = Q(title__icontains=keyword) | Q(content__icontains=keyword)
        ads = ads.filter(q)
    else:
        keyword = ''
    form = SearchForm(initial={'keyword': keyword})
    paginator = Paginator(ads, 2)
    if 'page' in request.GET:
        page_num = request.GET['page']
    else:
        page_num = 1
    page = paginator.get_page(page_num)
    context = {'page': page, 'ads': page.object_list, 'form': form}
    return render(request, 'main/profile.html', context)


@login_required
def profile_ad_detail(request, rubric_pk, pk):
    ad = get_object_or_404(Ad, pk=pk)
    ais = ad.additionalimage_set.all()
    context = {'ad': ad, 'ais': ais}
    return render(request, 'main/profile_ad_detail.html', context)


@login_required
def profile_ad_add(request):
    if request.method == 'POST':
        form = AdForm(request.POST, request.FILES)
        if form.is_valid():
            ad = form.save()
            formset = AIFormSet(request.POST, request.FILES, instance=ad)
            if formset.is_valid():
                formset.save()
                messages.add_message(request, messages.SUCCESS, 'Объявление добавлено')
                return redirect('main:profile')
    else:
        form = AdForm(initial={'author': request.user.pk})
        formset = AIFormSet()
    context = {'form': form, 'formset': formset}
    return render(request, 'main/profile_ad_add.html', context)


@login_required
def profile_ad_change(request, pk):
    ad = get_object_or_404(Ad, pk=pk)
    if request.method == 'POST':
        form = AdForm(request.POST, request.FILES, instance=ad)
        if form.is_valid():
            ad = form.save()
            formset = AIFormSet(request.POST, request.FILES, instance=ad)
            if formset.is_valid():
                formset.save()
                messages.add_message(request, messages.SUCCESS, 'Объявление изменено')
                return redirect('main:profile')
    else:
        form = AdForm(instance=ad)
        formset = AIFormSet(instance=ad)
    context = {'form': form, 'formset': formset}
    return render(request, 'main/profile_ad_change.html', context)


@login_required
def profile_ad_delete(request, pk):
    ad = get_object_or_404(Ad, pk=pk)
    if request.method == "POST":
        ad.delete()
        messages.add_message(request, messages.SUCCESS, 'Объявление удалено')
        return redirect('main:profile')
    else:
        context = {'ad': ad}
        return render(request, 'main/profile_ad_delete.html')


# class-based контроллеры для регистрации, редактирования личных данных и удаления профиля пользователя
class BBLoginView(LoginView):
    template_name = 'main/login.html'


class BBLogoutView(LogoutView, LoginRequiredMixin):
    '''Страница выхода должна быть доступна только зарегистрированным пользователям,
    выполнившим вход. Поэтому в число суперклассов добавили LoginRequiredMixin'''
    template_name = 'main/logout.html'

class BBPasswordChangeView(SuccessMessageMixin, LoginRequiredMixin, PasswordChangeView):
    '''В качестве одного из суперклассов этого контроллера-класса мы указали примесь
LoginRequiredMixin, запрещающую доступ к контроллеру гостям, и примесь
SuccessMessageMixin, которая применяется для вывода всплывающих сообщений
об успешном выполнении операции.'''
    template_name = 'main/password_change.html'
    success_url = reverse_lazy('main:profile')
    success_message = "Ваш пароль был успешно изменен"


class ChangeUserInfoView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    """В процессе работы этот контроллер должен извлечь из модели AdvUser запись,
представляющую текущего пользователя, для чего ему нужно предварительно
получить ключ текущего пользователя. Получить его можно из объекта текущего
пользователя, хранящегося в атрибуте user объекта запроса.
В качестве одного из суперклассов этого контроллера-класса мы указали примесь
LoginRequiredMixin, запрещающую доступ к контроллеру гостям, и примесь
SuccessMessageMixin, которая применяется для вывода всплывающих сообщений
об успешном выполнении операции."""
    model = AdvUser
    template_name = 'main/change_user_info.html'
    form_class = ChangeUserInfoForm
    success_url = reverse_lazy('main:profile')
    success_message = "Ваши данные пользователя были изменены"

    def setup(self, request, *args, **kwargs):
        """Вероятно, наилучшее место для получения ключа текущего пользователя — метод
setup, наследуемый всеми контроллерами-классами от их общего суперкласса
view. Этот метод выполняется в самом начале исполнения контроллера-класса и
получает объект запроса в качестве одного из параметров. В переопределенном
методе setup () мы извлечем ключ пользователя и сохраним его в атрибуте user id."""
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)

    def get_object(self, queryset=None):
        """Извлечение исправляемой записи выполняем в методе get object, который контроллер-
класс унаследовал от примеси singieobjectMixin. В переопределенном методе
сначала учитываем тот момент, что набор записей, из которого следует извлечь
искомую запись, может быть передан методу с параметром queryset, а может
быть и не передан — в этом случае набор записей следует получить вызовом метода
get queryset (). После этого непосредственно ищем запись, представляющую
текущего пользователя."""
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


class RegisterUserView(CreateView):
    model = AdvUser
    template_name = 'main/register_user.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('main:register_done')


class RegisterDoneView(TemplateView):

main/templates/main/activation_done.html
{% extends 'layout/basic.html' %}

{% block title %}Активация выполнена{% endblock %}

{% block content %}
<h2>Активация</h2>
<p>Активация профиля прошла успешно!</p>
<p><a href="{% url 'main:login' %}">Войти на сайт</a></p>
{% endblock %}

main/templates/main/bad_signature.html
{% extends 'layout/basic.html' %}

{% block title %}Ошибка активации{% endblock %}

{% block content %}
<h2>Активация</h2>
<p>Активация профиля прошла неудачно</p>
<p><a href="{% url 'main:register' %}">Зарегистрироваться повторно</a></p>
{% endblock %}

main/templates/main/by_rubric.html
{% extends 'layout/basic.html' %}

{% load thumbnail %}
{%  load static %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}

{% block title %}{{ rubric }}{% endblock %}

{% block content %}
<h2 class="mb-2">{{ rubric }}</h2>
<div class="container-fluid mb-2">
    <div class="row">
        <div class="col">&nbsp;</div>
        <form class="col-dm-auto form-inline">
            {% bootstrap_form form show_label=False %}
            <br>
            {% bootstrap_button content="Поиск" button_type='submit' %}
        </form>
    </div>
</div>
{% if ads %}
<ul class="list-unstyled">
    {% for ad in ads %}
    <li class="media my-5 p-3 border">
        {% url 'main:detail' rubric_pk=rubric.pk pk=ad.pk as url %}
        <a href="{{ url }}{{ all }}">
        {% if ad.image %}
        <img class="mr-3" src="{% thumbnail ad.image 'default' %}">
        {% else %}
        <img class="mr-3" src="{% static 'main/empty.jpg' %}">
        {% endif %}
        </a>
        <div class="media-body">
            <h3><a href="{{ url }}{{ all }}">
                {{ ad.title }}</a></h3>
            <div {{ ad.content }}></div>
            <p class="text-right font-weight-bold">{{ ad.price }} руб.</p>
            <p class="text-right font-italic">{{ ad.created_at }}</p>
        </div>
    </li>
    {% endfor %}
</ul>
{% bootstrap_pagination page url=keyword %}
{% endif %}
{% endblock %}

main/templates/main/change_user_info.html
{% extends 'layout/basic.html' %}

{% load crispy_forms_tags %}

{% block title %}Изменение данных пользователя{% endblock %}

{% block content %}
<h2>Изменение данных пользователя {{ user.username }}</h2>
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-primary mt-3" type="submit">Сохранить</button>
</form>
{% endblock %}

main/templates/main/delete_user.html
{% extends 'layout/basic.html' %}

{% load crispy_forms_tags %}

{% block title %}Удаление пользователя{% endblock %}

{% block content %}
<h2>Удаление пользователя {{ object.username }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
    <button class="btn btn-primary mt-3" type="submit">Удалить</button>
    </form>
{% endblock %}

main/templates/main/detail.html
{% extends 'layout/basic.html' %}

{% load bootstrap4 %}

{% block title %}{{ ad.title }} - {{ ad.rubric.name }}{% endblock %}

{% block content %}
<div class="container-fluid mt-3">
    <div class="row">
        {% if ad.image %}
        <div class="col-md-auto"><img src="{{ ad.image.url }}" class="main-image"></div>
        {% endif %}
        <div class="col">
            <h2>{{ ad.title }}</h2>
            <p>{{ ad.content }}</p>
            <p class="font-weight-bold">{{ ad.price }} руб.</p>
            <p>{{ ad.contacts }}</p>
            <p class="text-right font-italic">Добавлено {{ ad.created_at }}</p>
        </div>
    </div>
</div>
{% if ais %}
<div class="d-flex justify-content-between flex-wrap mt-5">
    {% for ai in ais %}
    <div>
        <img class="additional-image" src="{{ ai.image.url }}">
    </div>
    {% endfor %}
</div>
{% endif %}
<p><a href="{% url 'main:by_rubric' pk=ad.rubric.pk %}{{ all }}">Назад</a></p>
<h4 class="mt-5">Добавить новый комментарий</h4>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons submit='Добавить' %}{% endbuttons %}
</form>
    {% if comments %}
    <div class="mt-5">
    <h2>Комментарии</h2>
    {% for comment in comments %}
    <div class="my-2 p-2 border">
        <h5>{{ comment.author }}</h5>
        <p>{{ comment.content }}</p>
        <p class="text-right font-italic">{{ comment.created_at }}</p>
    </div>
    {% endfor %}
    </div>
    {% endif %}

{% endblock %}

main/templates/main/index.html
{% extends 'layout/basic.html' %}

{% load thumbnail %}
{% load static %}
{% load bootstrap4 %}
{% load crispy_forms_tags %}

{% block search_form %}

<div class="input-group">
    {{ form|crispy }}
    <span class="input-group-btn">
    <button class="btn btn-primary ml-3" type="submit">Поиск</button>
    </span>
</div>
{% endblock %}

{% block content %}
<div class="container-fluid mb-2 border-bottom">
    <div class="row">
        <div class="col">&nbsp;</div>
        <form class="col-dm-auto form-inline pb-3">
            {% bootstrap_form form show_label=False %}
            <br>
            {% bootstrap_button content="Поиск" button_type='submit' %}
        </form>
    </div>
</div>
<div class="container-fluid">
<h2 class="display-5 fw-bold text-center">Все объявления</h2>
{% if ads %}
<ul class="list-unstyled">
    {% for ad in ads %}
    <li class="media my-5 p-3 border">
        {% url 'main:detail' rubric_pk=ad.rubric.pk pk=ad.pk as url %}
        <a href="{{ url }}{{ all }}">
        {% if ad.image %}
        <img class="mr-3" src="{% thumbnail ad.image 'default' %}">
        {% else %}
        <img class="mr-3" src="{% static 'main/empty.jpg' %}">
        {% endif %}
        </a>
        <div class="media-body">
            <h3><a href="{{ url }}{{ all }}">
                {{ ad.title }}</a></h3>
            <div {{ ad.content }}></div>
            <p class="text-right font-weight-bold">{{ ad.price }} руб.</p>
            <p class="text-right font-italic">{{ ad.created_at }}</p>
        </div>
    </li>
    {% endfor %}
</ul>
{% bootstrap_pagination page url=keyword %}
{% endif %}
{% endblock %}

main/templates/main/logout.html
{% extends 'layout/basic.html' %}

{% block title %}Выход{% endblock %}

{% block content %}
<h2>Выход</h2>
<p>Вы успешно вышли из своего профиля</p>
{% endblock %}

main/templates/main/profile.html
{% extends 'layout/basic.html' %}

{% load thumbnail %}
{%  load static %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}


{% block title %}Профиль пользователя{% endblock %}

{% block content %}
<h2>Профиль пользователя {{ user.username }}</h2>
{% if user.first_name and user.last_name %}
<p>Здравствуйте, {{ user.first_name }} {{ user.last_name }}!</p>
<div class="container-fluid mb-2">
    <div class="row">
        <div class="col">&nbsp;</div>
        <form class="col-dm-auto form-inline">
            {% bootstrap_form form show_label=False %}
            <br>
            {% bootstrap_button content="Поиск" button_type='submit' %}
        </form>
    </div>
</div>
<div class="container-fluid">
<h2 class="display-5 fw-bold text-center">Ваши объявления</h2>
{% if ads %}
<ul class="list-unstyled">
    {% for ad in ads %}
    <li class="media my-5 p-3 border">
        {% url 'main:detail' rubric_pk=ad.rubric.pk pk=ad.pk as url %}
        <a href="{{ url }}{{ all }}">
        {% if ad.image %}
        <img class="mr-3" src="{% thumbnail ad.image 'default' %}">
        {% else %}
        <img class="mr-3" src="{% static 'main/empty.jpg' %}">
        {% endif %}
        </a>
        <div class="media-body">
            <h3><a href="{{ url }}{{ all }}">
                {{ ad.title }}</a></h3>
            <div {{ ad.content }}></div>
            <p class="text-right font-weight-bold">{{ ad.price }} руб.</p>
            <p class="text-right font-italic">{{ ad.created_at }}</p>
            <p class="text-start mt-3">
                <a href="{% url 'main:profile_ad_change' pk=ad.pk %}">Изменить</a>
                <a href="{% url 'main:profile_ad_delete' pk=ad.pk %}">Удалить</a>
            </p>
        </div>
    </li>
    {% endfor %}
</ul>
{% bootstrap_pagination page url=keyword %}
{% endif %}
{% else %}
<p>Здравствуйте!</p>
<h3>Чтобы разместить объявление, войдите под своей учетной записью или зарегистрируйтесь</h3>
{% endif %}
{% endblock %}

main/templates/main/profile_ad_change.html
{% extends 'layout/basic.html' %}

{% load crispy_forms_tags %}

{% block title %}Редактирование объявления{% endblock %}

{% block content %}
<h2>Редактирование объявления</h2>
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-primary mt-3" type="submit">Сохранить</button>

</form>
{% endblock %}

main/templates/main/profile_ad_delete.html
{% extends 'layout/basic.html' %}

{% load crispy_forms_tags %}

{% block title %}Удаление объявления{% endblock %}

{% block content %}
<h2>Удаление объявления {{ ad }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
    <button class="btn btn-primary mt-3" type="submit">Удалить</button>
    </form>
{% endblock %}

main/templates/main/register_done.html
{% extends 'layout/basic.html' %}

{% block title %}Регистрация завершена{% endblock %}

{% block content %}
    <h2>Регистрация</h2>
    <p>Регистрация пользователя завершена.</p>
    <p>На адрес электронной почты, указанный при регистрации, выслано письмо для активации</p>
{% endblock %}

main/templates/main/register_user.html
{% extends 'layout/basic.html' %}

{% load crispy_forms_tags %}

{% block title %}Регистрация{% endblock %}

{% block content %}
    <h2>Регистрация нового пользователя</h2>
    <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="hidden" name="next" value="{{ next }}">
    <button class="btn btn-primary mt-3" type="submit">Зарегистрироваться</button>
    </form>
{% endblock %}

main/templates/main/user_is_activated.html
{% extends 'layout/basic.html' %}

{% block title %}Пользователь уже активирован{% endblock %}

{% block content %}
<h2>Активация</h2>
<p>Пользователь с таким именем был активирован ранее.</p>
<p><a href="{% url 'main:login' %}">Войти на сайт</a></p>
{% endblock %}